name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  lint-and-quality-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install -r requirements.txt

      - name: Check for necessary file
        run: |
          if [ ! -f "config.json" ]; then
            echo "The necessary file config.json is missing. Please add it to the repository."
            exit 1
          else
            echo "config.json found. Proceeding with the pipeline."
          fi

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
    
      - name: Run pylint
        run: |
          pylint --disable=C0103,C0111 **/*.py


  build-and-test-python:
    needs: lint-and-quality-check
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código
        uses: actions/checkout@v2
      
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Executar testes unitários
        run: |
          pytest
          
  build-docker:
    runs-on: ubuntu-latest
    needs: 
    - build-and-test-python
    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Construir e publicar a aplicação Docker com versionamento
        run: |
          docker build -t python-webapp-cicd .
          docker tag python-webapp-cicd ${{ secrets.DOCKER_USERNAME }}/python-webapp-cicd:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ${{ secrets.DOCKER_USERNAME }}/python-webapp-cicd:latest

  make-artifact:
    runs-on: ubuntu-latest
    needs: 
    - build-and-test-python
    - build-docker      
    steps:
      - name: Checar o código
        uses: actions/checkout@v2
      - name: Build zip file
        run: |
          mkdir -p artifact
          cp -r ./requirements.txt Dockerfile app.py test_main.py ./artifact
          zip -r artifact/python-webapp-cicd.zip ./artifact

      - name: Github Actions Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: '${{ github.ref_name }}-${{ github.sha }}'
          release_name: 'Release ${{ github.ref_name }}-${{ github.sha }}'
          body: 'Release for ${{ github.ref_name }}'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifact/python-webapp-cicd.zip
          asset_name: python-webapp-cicd.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  deploy-to-staging:
    runs-on: ubuntu-latest
    needs: 
    - make-artifact
    if: success()
    environment:
      name: staging
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Deploy para ambiente de staging
        run: |
          echo "Simulando deploy para o ambiente de staging..."
          # Cenario em que o ambiente staging existe
          # docker pull ${{ secrets.DOCKER_USERNAME }}/python-webapp-cicd:staging
          # docker stop python-webapp-cicd || true
          # docker rm python-webapp-cicd || true
          # docker run -d --name python-webapp-cicd -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/python-webapp-cicd:staging

      - name: Verificar deploy
        run: |
          echo "Simulando verificação do deploy no ambiente de staging..."
          # curl http://localhost:8080/health || exit 1

  notify_failure:
    runs-on: ubuntu-latest
    if: failure()
    needs:
      - build-and-test-python
      - build-docker
      - make-artifact
      - deploy-to-staging
    steps:
      - name: Notificar desenvolvedor sobre falha via e-mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: 'Falha no Pipeline CI/CD'
          body: |
            O pipeline CI/CD falhou em uma das etapas.
            
            A falha ocorreu na etapa: ${{ job.status == 'failure' && github.job || 'desconhecida' }}.
            
            Detalhes da falha:
            - Job que falhou: ${{ github.job }}
            - Workflow: ${{ github.workflow }}
            - Repositório: ${{ github.repository }}
            - Branch: ${{ github.ref }}
            
            Verifique os logs no GitHub Actions para mais detalhes:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          to: dasilva.guilherme.582@gmail.com
          from: ${{ secrets.SMTP_USERNAME }}
