name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o código
        uses: actions/checkout@v2
      
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Executar testes unitários
        run: |
          pytest
      
      - name: Construir a aplicação Docker
        run: |
          docker build -t python-webapp-cicd .
      
      - name: Armazenar artefato como release do GitHub
        uses: actions/upload-artifact@v2
        with:
          name: python-webapp-cicd
          path: ./path/to/artifact

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Aprovação do deploy
        uses: hmarr/approve-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          approvers: 'user-or-group-name'
      
      - name: Deploy para ambiente de teste
        run: |
          # Comando para realizar o deploy da aplicação no ambiente de teste.
